### ISSUE TITLE
Help me understand how this compares to native apps

### ISSUE THREAD

**Issue by domenic** [slightlyoff/StorageDurability#3]
As the explainer says,

> Native application platforms do not suffer these indignities, instead providing durable storage as the default.

Why can't we do the same by default for web apps? Given the [HTML5 Hard Disk Filler API](http://feross.org/fill-disk/), I assume it's not a concern that websites could maliciously fill up your hard drive---they can already do that.

**Comment by jakearchibald** [comment]
Without storage durability, the flow should be:
1. User visits HTML5 disk filler
2. Disk becomes full
3. Browser drops all storage it has

With durability:
1. User visits HTML5 disk filler
2. It asks for durable storage permission
3. Disk becomes full
4. Browser drops all non-durable storage it has
5. If the device is still under storage pressure (eg, because the user granted permission)
   1. OS announces the disk is full, potentially highlighting HTML5 disk filler as the primary cause
   2. User removes the offending apps & origins

**Comment by domenic** [comment]
I think I see. My understanding is that browsers don't actually do step 3 right now, but we can consider that an implementation bug?

Probably can roll this up under #4 in that case, so closing.
